backend_principal:
    path:     /principal
    defaults: { _controller: BackendBundle:Default:index }

backend_login:
    path:   /login
    defaults: {_controller: BackendBundle:Default:login}

backend_login_check:
    path: /login_check

backend_logout:
    path: /logout

envio_archivos:
    path:    /envioarchivo
    defaults: { _controller: BackendBundle:Default:envio }

listar_afiliados:
    path:   /listaafiliados
    defaults: {_controller: BackendBundle:Default:listarAfiliado}

listar_usuarios:
   path: /listausuarios
   defaults: {_controller: BackendBundle:Default:listarUsuario}

cambiar_password_usuarios:
   path: /cambiopassword/{id}
   defaults: {_controller: BackendBundle:Default:cambiarPassword}