<?php

namespace Diloog\PagoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstadoDeDeudaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoDeDeudaRepository extends EntityRepository
{
    public function findUltimaDeudaActiva($afiliado)
    {
        $em = $this->getEntityManager();
        $dql =  "SELECT  e FROM PagoBundle:EstadoDeDeuda e
                WHERE e.afiliado = :afiliado
                AND e.pagada = false
                AND e.activa = true";
        $consulta = $em->createQuery($dql);
        $consulta->setParameter('afiliado', $afiliado);
        $consulta->setMaxResults(1);
        return $consulta->getSingleResult();

    }
}
