<?php

namespace Diloog\PagoBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;

/**
 * EstadoDeDeudaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagoRepository extends EntityRepository
{
    public function findUltimosPagos($afiliado)
    {
        $em = $this->getEntityManager();
	    $pagos = array();


        $dql1 = "SELECT e FROM PagoBundle:EstadoDeDeuda e
		         WHERE e.afiliado = :afiliado
				 AND e.pagada = true";
        $consulta1 = $em->createQuery($dql1);
        $consulta1->setParameter('afiliado', $afiliado);
		$consulta1->setMaxResults(5);
        $deudas = $consulta1->getResult();
      //  ld($deudas);


        $dql2 =  "SELECT  p FROM PagoBundle:Pago p
                WHERE p.estadoDeuda = :estadodeuda";
        foreach($deudas as $deuda){

            $consulta2 = $em->createQuery($dql2);
            $consulta2->setParameter('estadodeuda', $deuda);
            $consulta2->setMaxResults(1);
            $pago = $consulta2->getOneOrNullResult();
            //ld($pago);
            $pagos[] = $pago;

        }
      //  ld($pagos);
        return $pagos;

    }

    public function findPagosSinProcesar()
    {
        $em = $this->getEntityManager();

        $dql =  "SELECT  p FROM PagoBundle:Pago p
                WHERE p.procesado = false";

            $consulta = $em->createQuery($dql);
            $pagos = $consulta->getResult();

        return $pagos;

    }

}
