pago:
    resource: "@PagoBundle/Resources/config/routing.yml"
    prefix:   /

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /

afiliado:
    resource: "@AfiliadoBundle/Resources/config/routing.yml"
    prefix:   /

