security:
   firewalls:
      frontend:
        pattern: ^/*
        anonymous: ~
        form_login:
          login_path: afiliado_login
          check_path: afiliado_login_check
          default_target_path: /afiliado/principal
        remember_me:
          key: cgcet_35832
          lifetime: 3600
        logout:
          path: afiliado_logout
          target: /afiliado/login
   access_control:
        - { path: ^/afiliado/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/afiliado/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/afiliado/*, roles: ROLE_USUARIO }
   providers:
     usuarios:
        entity: { class: Diloog\AfiliadoBundle\Entity\Afiliado, property: alias }
   encoders:
        Diloog\AfiliadoBundle\Entity\Afiliado: plaintext

