AfiliadoBundle_tarjeta:
    resource: "@AfiliadoBundle/Resources/config/routing/tarjeta.yml"
    prefix:   /tarjeta

afiliado_principal:
    path:     /principal
    defaults: { _controller: AfiliadoBundle:Default:index }


pagina_ayuda:
    path:     /ayuda
    defaults: {_controller: AfiliadoBundle:Default:ayuda}

prueba_pago:
    path:    /pagoprueba
    defaults: {_controller: AfiliadoBundle:Default:pagoprueba}

procesar_pago:
   path:   /procesopago/{referencia}
   defaults: {_controller: AfiliadoBundle:Default:procesamientoPago}

estado_deuda:
    path:   /misdeudas
    defaults: {_controller: AfiliadoBundle:Default:estadoDeudaMostrar}

deuda_prueba_imprimir:
    path: /deudaimprimir
    defaults: {_controller: AfiliadoBundle:Default:pruebaImprimir}

crear_usuario_prueba:
    path: /crearusuario
    defaults: {_controller: AfiliadoBundle:Default:obtenerUsuarioPrueba}

afiliado_login_check:
    path: /login_check

afiliado_logout:
    path: /logout

afiliado_login:
    path: /login
    defaults: { _controller: AfiliadoBundle:Default:login }

datos_afiliado:
    path: /datos
    defaults: {_controller: AfiliadoBundle:Datos:index}

cambio_password:
    path: /cambiopassword
    defaults: {_controller: AfiliadoBundle:Datos:cambioPassword}

