afiliado_principal:
    path:     /principal
    defaults: { _controller: AfiliadoBundle:Default:index }


pagina_ayuda:
    path:     /ayuda
    defaults: {_controller: AfiliadoBundle:Default:ayuda}

afiliado_login_check:
    path: /login_check

afiliado_logout:
    path: /logout

afiliado_login:
    path: /login
    defaults: { _controller: AfiliadoBundle:Default:login }
